### ISSUE TITLE
E490: No fold found

### ISSUE THREAD

**Issue by roseperrone** [lukaszkorecki/workflowish#9]
When I type the command "za" anywhere in sample.wofl, vim reports "E490: No fold found". What might be wrong with my setup?

**Comment by lukaszkorecki** [comment]
@roseperrone Since I switched to Emacs I can't help much :-/

@flugsio @hangtwenty - any ideas?

**Comment by flugsio** [comment]
@roseperrone peeking at your vimrc suggests you might need to add `filetype plugin indent on`, just place it under `syntax on`

You can run this to debug `:verbose set syntax filetype foldmethod foldexpr` it should output something like this from a wofl file

```
  syntax=workflowish
        Last set from /usr/share/vim/vim74/syntax/syntax.vim
  filetype=workflowish
        Last set from ~/code/dotfiles/vim/bundle/workflowish/ftdetect/workflowish.vim
  foldmethod=expr
        Last set from ~/code/dotfiles/vim/bundle/workflowish/ftplugin/workflowish.vim
  foldexpr=WorkflowishCompactFoldLevel(v:lnum)
        Last set from ~/code/dotfiles/vim/bundle/workflowish/ftplugin/workflowish.vim
```

**Comment by roseperrone** [comment]
Thanks! Still no luck. That prints:

```
  syntax=
        Last set from /usr/share/vim/vim73/syntax/syntax.vim
  filetype=
        Last set from ~/.vim/view/~=+Desktop=+sample.wofl=
  foldmethod=manual
        Last set from ~/.vim/view/~=+Desktop=+sample.wofl=
  foldexpr=0
        Last set from ~/.vim/view/~=+Desktop=+sample.wofl=

```

[Here's my (somewhat crufty) vimrc](https://github.com/roseperrone/dotfiles/blob/master/vimrc).

**Comment by flugsio** [comment]
I tried your new conf and installed pathogen, it works with workflowish in ~/.vim/bundle/workflowish

It now fails due to loading the old view https://github.com/roseperrone/dotfiles/blob/master/vimrc#L26
As you can see from the verbose output it overwrites the last 3 settings from the view file, so delete that file. When I tested your old conf and then new, syntax was still set correctly though, so there might be something else wrong still.

@lukaszkorecki here you see why i didn't like that mkview workaround, it practically made debugging really hard as changes in vimrc didn't really take effect ;)

my structure for reference

```
$ tree ~/.vim/autoload ~/.vim/bundle
/home/flugsio/.vim/autoload
└── pathogen.vim
/home/flugsio/.vim/bundle
└── workflowish
    ├── ftdetect
    │   └── workflowish.vim
    ├── ftplugin
    │   └── workflowish.vim
    ├── Gemfile
    ├── Gemfile.lock
    ├── Rakefile
    ├── README.markdown
    ├── sample.wofl
    ├── syntax
    │   └── workflowish.vim
    ├── t
    │   ├── compact_folds.vim
    │   ├── convert_from_workflowy.vim
    │   └── focus_mode.vim
    ├── VimFlavor
    └── VimFlavor.lock
```

**Comment by roseperrone** [comment]
Deleting line 26 makes it work. Thank you!

**Comment by Archsx** [comment]
I got the same problem,but I didn't "set paste" in .vimrc,what should I do?
